jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Cache the Maven packages to speed up build
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Build and test
      run: mvn clean install
    - continue-on-error: true
      name: Package
      run: "sudo apt-get install -qq genisoimage\nmvn package -pl ugs-classic assembly:assembly\
        \ -DskipTests=true          \nmvn package -pl ugs-platform/application -P\
        \ create-macosx-x64-package,create-macosx-aarch64-package,create-win32-package,create-win64-package,create-linux-x64-package,create-linux-arm-package,create-linux-aarch64-package\
        \ -DskipTests=true\n"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Upload binaries to snapshot release
      uses: xresloader/upload-to-github-release@v1
      with:
        file: ugs-classic/target/UniversalGcodeSender.zip;ugs-platform/application/target/macosx-*-ugs-platform-app-*.dmg;ugs-platform/application/target/linux-*-ugs-platform-app*.tar.gz;ugs-platform/application/target/win-ugs-platform-app-*.zip;ugs-platform/application/target/win64-ugs-platform-app-*.zip;ugs-platform/application/target/ugs-platform-app-*.zip
        overwrite: true
        prerelease: true
        tag_name: nightly
name: Nightly build
on:
  repository_dispatch:
    types: trigger-ga___nightly.yaml
