jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Cache the Maven packages to speed up build
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Build and test
      run: mvn clean install
name: Build and test
on:
  repository_dispatch:
    types: trigger-ga___pr.yml
